/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void ecs_static_model__add(ecs_t* ecs, entity_id_t ent)
;

boolean ecs_static_model__get_property
	(
	ecs_t*						ecs, 
	entity_id_t					ent,
	uint32_t					property_idx, 
	ecs_component_prop_t*		out__property
	)
;

void ecs_static_model__load(ecs_t* ecs, entity_id_t ent, lua_script_t* lua)
;

void ecs_static_model__register(ecs_t* ecs)
;
