/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void _ed_cmd__set_component_property(void* context, _ed_undo_cmd_val_t* old_val, _ed_undo_cmd_val_t* new_val)
;
