/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static _ed_dialog_result_t show_dialog(_ed_ui_open_file_dialog_t* dialog)
;
