/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static _ed_undo_cmd_t* create(_ed_undo_t* undo)
;

static void free_if_need(_ed_undo_t* undo, uint32_t idx)
;
