/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void _ed_ui_open_file_dialog__construct(_ed_ui_open_file_dialog_t* dialog, _ed_t* ed)
;

void _ed_ui_open_file_dialog__destruct(_ed_ui_open_file_dialog_t* dialog)
;

void _ed_ui_open_file_dialog__think(_ed_ui_open_file_dialog_t* dialog)
;
