/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void _ed_ui_properties__construct(_ed_ui_properties_t* prop, _ed_t* ed)
;

void _ed_ui_properties__destruct(_ed_ui_properties_t* prop)
;

void _ed_ui_properties__think(_ed_ui_properties_t* prop)
;
