/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static void char_callback(GLFWwindow* window, unsigned int c)
;

static void cursor_pos_callback(GLFWwindow* window, double xpos, double ypos)
;

static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
;

static void mouse_button_callback(GLFWwindow* window, int button, int action, int mods)
;

static void mouse_scroll_callback(GLFWwindow* window, double xoffset, double yoffset)
;

static void resize_callback(GLFWwindow* window, int width, int height)
;

static void window_close_callback(GLFWwindow* window)
;
