/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/**
Shuts down up the app.
*/
static void shutdown()
;

/**
Sets up the app.
*/
static void startup()
;
