/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/**
Constructs a material.

@param material The material to construct.
@param gpu The GPU context.
@param create_info The material info.
*/
void gpu_material__construct(gpu_material_t* material, gpu_t* gpu, gpu_material_create_info_t* create_info)
;

/**
Constructs a material using a material script file.

@param material The material to construct.
@param gpu The GPU context.
@param filename The file that defines the material.
*/
void gpu_material__construct_from_file(gpu_material_t* material, gpu_t* gpu, const char* filename)
;

/**
Constructs a material using a material script file.

@param material The material to construct.
@param gpu The GPU context.
@param tinymat The material from the tinyobj lib.
*/
void gpu_material__construct_from_tinyobj(gpu_material_t* material, gpu_t* gpu, tinyobj_material_t* tinymat)
;

/**
Destructs a material.

@param material The material to destruct.
@param gpu The GPU context.
*/
void gpu_material__destruct(gpu_material_t* material, gpu_t* gpu)
;
