/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static void file_reader
	(
	const char*		filename,
	int				is_mtl,
	const char*		obj_filename,
	char**			buf,
	size_t*			len
	)
;
