/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static void load_material_from_create_info(gpu_material_t* material, gpu_t* gpu, gpu_material_create_info_t* create_info)
;

static void load_material_from_script(gpu_material_t* material, gpu_t* gpu, const char* filename)
;

static void load_material_from_tinyobj(gpu_material_t* material, gpu_t* gpu, tinyobj_material_t* tinymat)
;
