/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void jetz__construct(app_t* app)
;

void jetz__destruct(app_t* app)
;

void jetz__init_app_intf(app_intf_t* intf)
;

void jetz__run_frame(app_t* app)
;

boolean jetz__should_exit(app_t* app)
;

_jetz_t* _jetz__from_base(app_t* app)
;
