/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/** Gets a string representation of a log level. */
static const char* get_log_level_str(uint8_t level)
;
