/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/**
Initializes a logging context.
@param log The context to init.
*/
void kk_log__construct(kk_log_t* log)
;

/**
Destructs a logging context.
@param log The context to destruct.
*/
void kk_log__destruct(kk_log_t* log)
;

/**
Logs a message.

@param log The logging context.
@param level The log level.
@param msg The message to log.
*/
void kk_log__msg(kk_log_t* log, uint8_t level, const char* in_msg)
;

/**
Logs a message and includes the source filename and line number where the message originated from.

@param log The logging context.
@param level The log level.
@param filename The source filename.
@param line The line number in the source file.
@param msg_fmt The message to log.
*/
void kk_log__msg_with_source
	(
	kk_log_t*			log, 
	uint8_t				level, 
	const char*			filename, 
	int					line, 
	const char*			msg_fmt, 
	...
	)
;

/**
Registers a logging target for all log levels.

@param log The logging context.
@param target The target callback function to call.
*/
void kk_log__register_target(kk_log_t* log, kk_log_target_func target)
;
