/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static void load_world_file(kk_world_t* world, const char* filename)
;
