/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/**
Loads a world.
@param world The world to construct.
@param ecs The entity component system to use.
@param filename The name of the world file.
*/
void kk_world__construct(kk_world_t* world, const char* filename)
;

/**
Destructs a world.
@param world The world to destruct.
*/
void kk_world__destruct(kk_world_t* world)
;

void kk_world__export_lua(kk_world_t* world, const char* filename)
;
