/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

_pspgu_t* _pspgu__get_context(gpu_t* gpu)
;
