/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void _pspgu_static_model__construct
	(
	_pspgu_static_model_t*		model,
	_pspgu_t*					ctx,
	const tinyobj_t*			obj
	)
;

void _pspgu_static_model__destruct(_pspgu_static_model_t* model)
;

void _pspgu_static_model__render
	(
	_pspgu_static_model_t*		model,
	_pspgu_t*					ctx
	)
;
