/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void _pspgu_static_mesh__construct
	(
	_pspgu_static_mesh_t*		mesh,
	_pspgu_t*					ctx,
	const tinyobj_t*			obj,
	const tinyobj_shape_t*		obj_shape
	)
;

void _pspgu_static_mesh__destruct(_pspgu_static_mesh_t* mesh)
;

void _pspgu_static_mesh__render
	(
	_pspgu_static_mesh_t*		mesh,
	_pspgu_t*					ctx
	)
;
