/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/** Loads mesh data. */
static void load_mesh
	(
	_pspgu_static_mesh_t*		mesh,
	_pspgu_t*					ctx,
	const tinyobj_t*			obj,
	const tinyobj_shape_t*		obj_shape
	)
;
