/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/** Initializes the meshes in the model. */
static void create_meshes(_pspgu_static_model_t* model, _pspgu_t* ctx, const tinyobj_t* obj)
;

/** Destroys the meshes in the model. */
static void destroy_meshes(_pspgu_static_model_t* model)
;
