/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void _pspgu_plane__construct
	(
	_pspgu_plane_t*				plane,
	_pspgu_t*					ctx
	)
;

void _pspgu_plane__destruct(_pspgu_plane_t* plane)
;

void _pspgu_plane__render
	(
	_pspgu_plane_t*				plane,
	_pspgu_t*					ctx
	)
;

void _pspgu_plane__update_verts
	(
	_pspgu_plane_t* 			plane,
	_pspgu_t* 					ctx,
	kk_vec3_t 					verts[4]
	)
;
