/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void _pspgu_material__construct
	(
	_pspgu_material_t*			material,
	_pspgu_t*					ctx,
	kk_vec3_t					diffuse_color,
	_pspgu_texture_t*			diffuse_texture
	)
;

void _pspgu_material__destruct(_pspgu_material_t* material)
;
