/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/**
Creates a GPU interface for the PSP GPU.
*/
void pspgu__init_gpu_intf(gpu_intf_t* intf)
;
