/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

void _pspgu_texture__construct
	(
	_pspgu_texture_t*			texture,
	_pspgu_t*					ctx,
	void*						img,
	uint32_t					width,
	uint32_t					height,
	uint32_t					size_in_bytes
	)
;

void _pspgu_texture__destruct(_pspgu_texture_t* texture)
;
