/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/**
Constructs a static model.
*/
void vlk_static_model__construct
	(
	gpu_static_model_t*			base,
	gpu_t*						gpu,
	const tinyobj_t*			obj
	)
;

/**
Destructs a static model.
*/
void vlk_static_model__destruct(gpu_static_model_t* base, gpu_t* gpu)
;

/**
Renders the model to the picker buffer.
*/
void vlk_static_model__render_to_picker_buffer
	(
	gpu_static_model_t*		model, 
	gpu_t*					gpu, 
	gpu_window_t*			window, 
	gpu_frame_t*			frame,
	kk_vec4_t				color,
	ecs_transform_t*		transform
	)
;

_vlk_static_model_t* _vlk_static_model__from_base(gpu_static_model_t* base)
;

/**
Renders a static model. The appropriate pipeline must already be bound.
*/
void _vlk_static_model__render
	(
	_vlk_static_model_t*		model,
	VkCommandBuffer				cmd
	)
;
