/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static void create_buffer
	(
	_vlk_material_t*				material,
	gpu_material_t*					base,
	_vlk_dev_t*						device
	)
;

static void destroy_buffer(_vlk_material_t* material)
;
