/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/**
Constructs a Vulkan material.

@param base The base object.
@param device The Vulkan device.
*/
void vlk_material__construct
	(
	gpu_material_t*					base,
	gpu_t*							gpu
	)
;

/**
Destructs a material.
*/
void vlk_material__destruct(gpu_material_t* base, gpu_t* gpu)
;

_vlk_material_t* _vlk_material__from_base(gpu_material_t* base)
;
