/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static void create_material_set(_vlk_static_model_t* model, _vlk_dev_t* device)
;

static void create_meshes(_vlk_static_model_t* model, _vlk_dev_t* device, const tinyobj_t* obj)
;

static void destroy_material_set(_vlk_static_model_t* model)
;

static void destroy_meshes(_vlk_static_model_t* model)
;
