/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

/**
Constructs a static mesh.
*/
void _vlk_static_mesh__construct
	(
	_vlk_static_mesh_t*			mesh,
	_vlk_dev_t*					device,
	const tinyobj_t*			obj,
	const tinyobj_shape_t*		obj_shape
	)
;

/**
Destructs a static mesh.
*/
void _vlk_static_mesh__destruct(_vlk_static_mesh_t* mesh)
;

/**
Renders a static mesh. The appropriate pipeline must already be bound.
*/
void _vlk_static_mesh__render
	(
	_vlk_static_mesh_t*			mesh,
	VkCommandBuffer				cmd
	)
;
