/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static void create_picker_render_pass(_vlk_dev_t* dev)
;

static void destroy_picker_render_pass(_vlk_dev_t* dev)
;
