/*=========================================================
This file is automatically generated. Do not edit manually.
=========================================================*/

static void create_buffers
	(
	_vlk_static_mesh_t*			mesh,
	_vlk_dev_t*					dev,
	const tinyobj_t*			obj,
	const tinyobj_shape_t*		obj_shape
	)
;

static void destroy_buffers(_vlk_static_mesh_t* mesh)
;
